theme: minima
title: Welcome to my World
author: Ville Diesel
email: villedieselcreative@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is site for Ville Diesel Creative. I plan on updating this to make it as awesome as possible. 
  Stay tuned for more to come. I look forward to being a better programmer.

# social links
twitter_username: VilleDiesel # DO NOT include the @ character, or else the build will fail!
github_username:  villediesel # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
